/**
 * Métricas conhecidas pela camada de IA. Cada métrica declara unidade,
 * direção (maior é melhor / pior), thresholds saudáveis e a entidade
 * de origem. O motor de insights usa estas definições para escolher
 * visualizações, semáforos e textos automáticos.
 *
 * Para adicionar uma nova métrica:
 *  1. Defina aqui (id em snake_case).
 *  2. Implemente o cálculo em `insightEngine.ts` (em `computeMetric`).
 *  3. (Opcional) adicione threshold em `healthBands` para semáforo.
 */

import type { MetricDefinition } from "./types";

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  received_count: {
    id: "received_count",
    label: "Orçamentos recebidos",
    description: "Total de orçamentos criados no período.",
    unit: "count",
    domain: "operacional",
    entity: "budgets",
    direction: "up_is_good",
    related: ["throughput_per_week", "conversion_rate"],
  },
  backlog_count: {
    id: "backlog_count",
    label: "Backlog ativo",
    description: "Orçamentos em aberto (status operacional ativo).",
    unit: "count",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
    healthBands: { excellent: 4, healthy: 8, warning: 15, critical: 25 },
  },
  overdue_count: {
    id: "overdue_count",
    label: "Orçamentos vencidos",
    description: "Backlog com prazo `due_at` no passado.",
    unit: "count",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
    healthBands: { excellent: 0, healthy: 1, warning: 3, critical: 6 },
  },
  sla_on_time_pct: {
    id: "sla_on_time_pct",
    label: "SLA dentro do prazo",
    description: "Porcentagem do backlog ainda dentro do prazo.",
    unit: "percent",
    domain: "operacional",
    entity: "budgets",
    direction: "up_is_good",
    healthBands: { excellent: 95, healthy: 80, warning: 60, critical: 0 },
  },
  avg_lead_time_days: {
    id: "avg_lead_time_days",
    label: "Lead time médio (dias)",
    description: "Tempo médio entre criação e entrega ao comercial.",
    unit: "days",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
    healthBands: { excellent: 2, healthy: 4, warning: 7, critical: 14 },
  },
  median_lead_time_days: {
    id: "median_lead_time_days",
    label: "Lead time mediano (dias)",
    description: "Mediana do tempo entre criação e entrega — robusto a outliers.",
    unit: "days",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
  },
  throughput_per_week: {
    id: "throughput_per_week",
    label: "Throughput / semana",
    description: "Entregas ao comercial por semana no período.",
    unit: "count",
    domain: "operacional",
    entity: "budgets",
    direction: "up_is_good",
  },
  conversion_rate: {
    id: "conversion_rate",
    label: "Taxa de conversão",
    description: "% de orçamentos enviados que viram contrato fechado.",
    unit: "percent",
    domain: "comercial",
    entity: "budgets",
    direction: "up_is_good",
    healthBands: { excellent: 35, healthy: 25, warning: 15, critical: 0 },
  },
  win_rate: {
    id: "win_rate",
    label: "Win rate",
    description: "% de orçamentos com decisão (won/lost) que foram ganhos.",
    unit: "percent",
    domain: "comercial",
    entity: "budgets",
    direction: "up_is_good",
  },
  revenue_brl: {
    id: "revenue_brl",
    label: "Receita",
    description: "Soma do valor de contratos fechados no período.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
  },
  cost_brl: {
    id: "cost_brl",
    label: "Custo total",
    description: "Soma do `internal_cost` dos contratos fechados.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "down_is_good",
    reliability: "medium",
  },
  gross_margin_brl: {
    id: "gross_margin_brl",
    label: "Margem bruta (R$)",
    description: "Receita menos custo dos contratos fechados.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
  },
  gross_margin_pct: {
    id: "gross_margin_pct",
    label: "Margem bruta (%)",
    description: "Margem bruta como % da receita.",
    unit: "percent",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
    healthBands: { excellent: 35, healthy: 22, warning: 12, critical: 0 },
  },
  avg_ticket_brl: {
    id: "avg_ticket_brl",
    label: "Ticket médio",
    description: "Receita média por contrato fechado.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
  },
  portfolio_value_brl: {
    id: "portfolio_value_brl",
    label: "Valor em pipeline",
    description: "Valor potencial em todo o backlog ativo.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
  },
  weighted_pipeline_brl: {
    id: "weighted_pipeline_brl",
    label: "Pipeline ponderado",
    description: "Pipeline com probabilidade de fechamento por etapa.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
  },
  forecast_revenue_next_30d: {
    id: "forecast_revenue_next_30d",
    label: "Forecast 30 dias",
    description: "Projeção de receita para os próximos 30 dias com base em tendência e pipeline.",
    unit: "currency_brl",
    domain: "financeiro",
    entity: "budgets",
    direction: "up_is_good",
    reliability: "medium",
  },
  budget_age_days: {
    id: "budget_age_days",
    label: "Idade média do backlog (dias)",
    description: "Idade média dos orçamentos em aberto.",
    unit: "days",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
  },
  stalled_count: {
    id: "stalled_count",
    label: "Travados",
    description: "Itens parados em estágios de bloqueio (waiting_info, ready_for_review) há tempo.",
    unit: "count",
    domain: "operacional",
    entity: "budgets",
    direction: "down_is_good",
  },
  health_score: {
    id: "health_score",
    label: "Health score",
    description: "Saúde operacional consolidada (0–100).",
    unit: "score",
    domain: "operacional",
    entity: "budgets",
    direction: "up_is_good",
    healthBands: { excellent: 85, healthy: 70, warning: 50, critical: 0 },
  },
  data_completeness_pct: {
    id: "data_completeness_pct",
    label: "Completude dos dados",
    description: "% de campos relevantes preenchidos no período (custo, prazo, origem).",
    unit: "percent",
    domain: "core",
    entity: "budgets",
    direction: "up_is_good",
  },
  lead_to_budget_rate: {
    id: "lead_to_budget_rate",
    label: "Lead → Orçamento",
    description: "% de leads que viraram orçamento.",
    unit: "percent",
    domain: "comercial",
    entity: "clients",
    direction: "up_is_good",
  },
  loss_to_competitor_pct: {
    id: "loss_to_competitor_pct",
    label: "Perda p/ concorrente",
    description: "% de orçamentos perdidos com concorrente identificado.",
    unit: "percent",
    domain: "comercial",
    entity: "budget_lost_reasons",
    direction: "down_is_good",
  },
};

export function listMetrics(): MetricDefinition[] {
  return Object.values(METRIC_DEFINITIONS);
}

export function getMetric(id: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS[id];
}
